name: "Docker Buildx Build Publish"
description: "Generic Docker buildx action for building and publishing multi-platform Docker images"
author: "Jimmie Fulton <jimmie.fulton@gmail.com>"

# Define the inputs for this action
inputs:
  dockerfile-path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  context-path:
    description: "Build context path"
    required: false
    default: "."
  image-name:
    description: "Docker image name"
    required: true
  image-tag:
    description: "Docker image tag"
    required: false
    default: "latest"
  registry:
    description: "Container registry URL (required when push is true)"
    required: false
  push:
    description: "Whether to push the image to registry"
    required: false
    default: "true"
  build-args:
    description: "Build arguments for Docker build (multiline string)"
    required: false
    default: ""
  platforms:
    description: "Target platforms for multi-platform build"
    required: false
    default: "linux/amd64"
  secrets:
    description: "Build secrets to pass to the build context (multiline string, format: id=mysecret,src=/local/secret)"
    required: false
    default: ""
  load:
    description: "Load the built image into the local Docker daemon"
    required: false
    default: "false"
  outputs:
    description: "Output configuration (e.g., type=docker,dest=./image.tar)"
    required: false
    default: ""
  labels:
    description: "Metadata labels for the image (multiline string)"
    required: false
    default: ""
  annotations:
    description: "Manifest annotations (multiline string)"
    required: false
    default: ""
  cache-from:
    description: "Cache import configuration"
    required: false
    default: "type=gha"
  cache-to:
    description: "Cache export configuration"
    required: false
    default: "type=gha,mode=max"
  skip-setup:
    description: "Skip Docker Buildx setup (use when already configured)"
    required: false
    default: "false"
  builder-name:
    description: "Name of the buildx builder to use"
    required: false
    default: ""

# Define the outputs for this action
outputs:
  image-digest:
    description: "The digest of the built image"
    value: ${{ steps.build.outputs.digest }}
  image-metadata:
    description: "Build result metadata"
    value: ${{ steps.build.outputs.metadata }}
  image-uri:
    description: "Full image URI with registry and tag"
    value: ${{ steps.build.outputs.image-uri }}

# Define the runs configuration
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      if: ${{ inputs.skip-setup != 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.registry && format('{0}/{1}:{2}', inputs.registry, inputs.image-name, inputs.image-tag) || format('{0}:{1}', inputs.image-name, inputs.image-tag) }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        secrets: ${{ inputs.secrets }}
        outputs: ${{ inputs.outputs }}
        labels: ${{ inputs.labels }}
        annotations: ${{ inputs.annotations }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        builder: ${{ inputs.builder-name }}

    - name: Set image URI output
      shell: bash
      run: |
        if [ -n "${{ inputs.registry }}" ]; then
          echo "image-uri=${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
        else
          echo "image-uri=${{ inputs.image-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
        fi

# Define the branding for the action in the GitHub Marketplace
branding:
  icon: "award"
  color: "blue"